#!/bin/bash

# --- 1. Setup and Pathing ---
# Find the absolute directory where this bash script (and the python script) lives
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PYTHON_SCRIPT="$SCRIPT_DIR/autocrop_ocr.py"

if [ ! -f "$PYTHON_SCRIPT" ]; then
    echo "ERROR: Cannot find autocrop_ocr.py in $SCRIPT_DIR"
    exit 1
fi

# Set target directory to the first argument provided, or use current directory if empty
TARGET_DIR="${1:-.}"

# Convert to an absolute path so we can safely navigate around
TARGET_DIR=$(realpath "$TARGET_DIR")

if [ ! -d "$TARGET_DIR" ]; then
    echo "ERROR: Directory '$TARGET_DIR' does not exist."
    echo "Usage: ./batch_process.sh [/path/to/scan/folder]"
    exit 1
fi

# --- 2. Dependency Checks ---
echo "Verifying system dependencies..."
for cmd in tesseract exiftool; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "ERROR: System command '$cmd' is not installed or not in your PATH."
        exit 1
    fi
done

for module in cv2 pytesseract; do
    if ! python3 -c "import $module" &> /dev/null; then
        echo "ERROR: Python module '$module' is missing."
        exit 1
    fi
done

echo "All dependencies met!"
echo "Target directory: $TARGET_DIR"
echo "------------------------------------------------"

# --- 3. Main Processing Loop ---

# Navigate into the target directory so the Python script outputs files right there
cd "$TARGET_DIR" || exit

# Create the output directory inside the target folder
mkdir -p extracted_photos
shopt -s nullglob

for file in *.jpg; do
    # Skip files that were generated by our Python script
    if [[ "$file" == *"_photo_"* ]] || [[ "$file" == *"_label"* ]]; then
        continue
    fi

    echo "Processing scan: $file"
    
    # Run the Python script (using its absolute path) on the local file
    if python3 "$PYTHON_SCRIPT" "$file"; then
        mv "${file%.*}_photo_"*.jpg "${file%.*}_label.jpg" extracted_photos/ 2>/dev/null
    else
        echo "Warning: Python script encountered an error with $file"
    fi
    echo "------------------------------------------------"
done

echo "Batch processing complete! Check the '$TARGET_DIR/extracted_photos' folder."
